import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "@/app/context/CardContext";

const inter = Inter({ subsets: ["latin"] });

// const clashDisplay = localFont({
//   src: "/fonts/ClashDisplay-Variable.ttf",
//   variable: "--font-clash-display",
//   weight: "300 400",
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
      <CartProvider>
        <Navbar/>
        {children}
        <Footer/>
        </CartProvider>
        </body>
    </html>
  );
}
